[project]
name = "ec2-roller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34",
    "botocore>=1.34",
    "python-dotenv>=1.0",
    "rich>=13.7",
    "typer>=0.12",
]
